name: Code Coverage
on: [push, pull_request]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Coverage Report
        if: success()
        uses: codecov/codecov-action@v2
        with:
          files: ./codecov.xml
